### ISSUE TITLE
css style gets override by target website

### ISSUE THREAD

**Issue by Xadoy** [mysterytony/timelocker-chrome#3]
Step to reproduce:
1. add `douyu.com` into the list of urls
2. open [douyu.com](douyu.com)

Expected:
buttons should be visible.
Actual:
button style is polluted by the target website, and ui/ux is affected.
<img width="1766" alt="截屏2021-01-17 上午11 05 51" src="https://user-images.githubusercontent.com/9660951/104848676-1be0b180-58b4-11eb-9980-a3112670c062.png">

**Comment by mysterytony** [comment]
豁 斗鱼牛批
