### ISSUE TITLE
visiting pages that make calls to the blocked urls, will be blocked

### ISSUE THREAD

**Issue by mysterytony** [mysterytony/timelocker-chrome#4]
e.g. on a page with an embedded youtube video, and youtube.com is blocked, the video will just silently, not play

**Comment by Xadoy** [comment]
is this necessary???

**Comment by mysterytony** [comment]
this is a bug, currently it just silently block the embedded content, if it makes calls to URLs that are blocked

for the expected behaviour, we should allow it to play
